[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
prisma = "0.1.1"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlite = "0.31.1"
angular-units = "0.2.4"
meval = "0.2.0"
